name: CI for ML Project

on:
  push:
    branches:
      - master  # Triggers on push to the main branch
  pull_request:
    branches:
      - master  # Triggers on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on a Linux environment

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8 pandas numpy scikit-learn
        

    - name: Run tests with pytest
      run: |
        pytest ./starter/app

    - name: Run flake8 for linting
      run: |
        flake8 ./starter/app
